# Generated by Django 3.1.7 on 2021-05-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210404_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdegree',
            options={'verbose_name': 'Academic degree', 'verbose_name_plural': 'Academic degrees'},
        ),
        migrations.AlterModelOptions(
            name='academicrank',
            options={'verbose_name': 'Academic rank', 'verbose_name_plural': 'Academic ranks'},
        ),
        migrations.AlterModelOptions(
            name='businessform',
            options={'verbose_name': 'Business form', 'verbose_name_plural': 'Business forms'},
        ),
        migrations.AlterModelOptions(
            name='chair',
            options={'verbose_name': 'Chair', 'verbose_name_plural': 'Chairs'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.academicdegree', verbose_name='Academic degree'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.academicrank', verbose_name='Academic rank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.businessform', verbose_name='Business form'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.chair', verbose_name='Chair'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rate', verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Status'),
        ),
    ]
