# Generated by Django 3.1.7 on 2021-05-13 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorshipWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Curatorship work type')),
            ],
            options={
                'verbose_name': 'Curatorship work type',
                'verbose_name_plural': 'Curatorship work types',
            },
        ),
        migrations.CreateModel(
            name='InternationalCooperationWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Extracurricular work type')),
            ],
            options={
                'verbose_name': 'International cooperation work type',
                'verbose_name_plural': 'International cooperation work types',
            },
        ),
        migrations.CreateModel(
            name='OrgMethodWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Organizational methodical work type')),
            ],
            options={
                'verbose_name': 'Organizational methodical work type',
                'verbose_name_plural': 'Organizational methodical work types',
            },
        ),
        migrations.CreateModel(
            name='VocationalGuidanceWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.IntegerField(verbose_name='Fullname')),
                ('phone', models.DateField(verbose_name='Phone number')),
                ('educational_institution', models.CharField(max_length=255, verbose_name='Educational institution')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('parent_contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacts of parents')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Vocational guidance work',
                'verbose_name_plural': 'Vocational guidance works',
            },
        ),
        migrations.CreateModel(
            name='OrgMethodWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_name', models.TextField(blank=True, verbose_name='Prepared information name')),
                ('hours_1', models.IntegerField(blank=True, verbose_name='Hours count')),
                ('execution_period', models.DateField(verbose_name='Period of execution')),
                ('document', models.FileField(upload_to='uploads/', verbose_name='Supporting document')),
                ('org_method_work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_work.orgmethodworktype', verbose_name='Organizational methodical work type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Organizational methodical work',
                'verbose_name_plural': 'Organizational methodical works',
            },
        ),
        migrations.CreateModel(
            name='InternationalCooperationWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_1', models.IntegerField(blank=True, verbose_name='Hours count')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('completed', models.BooleanField(blank=True, null=True, verbose_name='Completion mark')),
                ('int_coop_work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_work.internationalcooperationworktype', verbose_name='International cooperation work type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'International cooperation work',
                'verbose_name_plural': 'International cooperation works',
            },
        ),
        migrations.CreateModel(
            name='CuratorshipWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of execution')),
                ('document', models.FileField(upload_to='uploads/', verbose_name='Supporting document')),
                ('cur_work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_work.curatorshipworktype', verbose_name='Curatorship work type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Curatorship work',
                'verbose_name_plural': 'Curatorship works',
            },
        ),
    ]
