# Generated by Django 3.1.7 on 2021-04-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalwork',
            options={'verbose_name': 'Educational work', 'verbose_name_plural': 'Educational works'},
        ),
        migrations.AlterModelOptions(
            name='educationalworktype',
            options={'verbose_name': 'Educational work type', 'verbose_name_plural': 'Educational work types'},
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='by_fact_1',
            field=models.IntegerField(blank=True, verbose_name='Fact 1 semester'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='by_fact_2',
            field=models.IntegerField(blank=True, verbose_name='Fact 2 semester'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='by_fact_annual',
            field=models.IntegerField(blank=True, verbose_name='Fact annual'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='by_plan_1',
            field=models.IntegerField(blank=True, verbose_name='Plan 1 semester'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='by_plan_2',
            field=models.IntegerField(blank=True, verbose_name='Plan 2 semester'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='by_plan_annual',
            field=models.IntegerField(blank=True, verbose_name='Plan annual'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='deviation_1',
            field=models.IntegerField(blank=True, verbose_name='Deviation 1 semester'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='deviation_2',
            field=models.IntegerField(blank=True, verbose_name='Deviation 2 semester'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='deviation_annual',
            field=models.IntegerField(blank=True, verbose_name='Deviation annual'),
        ),
        migrations.AlterField(
            model_name='educationalwork',
            name='education_work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_work.educationalworktype', verbose_name='Educational work type'),
        ),
        migrations.AlterField(
            model_name='educationalworktype',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип учебной работы'),
        ),
    ]
