# Generated by Django 3.1.7 on 2021-05-17 10:36

from django.db import migrations, models
import edu_work.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('edu_work', '0002_curatorshipwork_curatorshipworktype_internationalcooperationwork_internationalcooperationworktype_or'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtracurricularWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Extracurricular work type')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
            ],
            options={
                'verbose_name': 'Extracurricular work type',
                'verbose_name_plural': 'Extracurricular work types',
            },
        ),
        migrations.AddField(
            model_name='curatorshipwork',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='curatorshipwork',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='curatorshipworktype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='educationalwork',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='educationalwork',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='educationalworktype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='edumethodwork',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='edumethodwork',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='edumethodworktype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='internationalcooperationwork',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='internationalcooperationwork',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='internationalcooperationworktype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='orgmethodwork',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='orgmethodwork',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='orgmethodworktype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='vocationalguidancework',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval status'),
        ),
        migrations.AddField(
            model_name='vocationalguidancework',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='internationalcooperationworktype',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='International cooperation work type'),
        ),
        migrations.AlterField(
            model_name='orgmethodwork',
            name='document',
            field=models.FileField(upload_to=edu_work.validators.validators.upload_to, validators=[edu_work.validators.validators.validate_file_extension], verbose_name='Supporting document'),
        ),
    ]
