# Generated by Django 3.1.7 on 2021-04-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_work', '0002_auto_20210412_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduMethodWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Educational methodical work type')),
            ],
            options={
                'verbose_name': 'Educational methodical work type',
                'verbose_name_plural': 'Educational methodical work types',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Specialty name')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.AddField(
            model_name='educationalwork',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='educationalworktype',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Educational work type'),
        ),
        migrations.CreateModel(
            name='EduMethodWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_1', models.IntegerField(blank=True, verbose_name='Hours count')),
                ('by_plan', models.IntegerField(blank=True, verbose_name='Plan')),
                ('by_fact', models.IntegerField(blank=True, verbose_name='Fact')),
                ('edu_method_work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_work.edumethodworktype', verbose_name='Educational methodical work type')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_work.specialty', verbose_name='Specialty name')),
            ],
            options={
                'verbose_name': 'Educational work',
                'verbose_name_plural': 'Educational works',
            },
        ),
    ]
