# Generated by Django 3.1.7 on 2021-05-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_work', '0003_auto_20210427_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edumethodwork',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_work.specialty', verbose_name='Specialty'),
        ),
    ]
